### ISSUE TITLE
Peer to peer code review  - Hummingbird

### ISSUE THREAD

**Issue by xtrmdarc** [elmejdki/BookClone#26]
- Nice use of AWS S3
- Awesome project's design
- Add bidirectional (reflexive) friendship relationship
- Fix overflow on the header
- Fix overlapping on mobile view ( Login page)
- Well organized code
- Fix overflowing on sign up page
- Really good project
- Add some spacing to home's title
- Add styling on forgot password page

**Comment by elmejdki** [comment]
thank you guys for the review it was really helpfull
